@FranchiseGraph.Server_HostAddress = http://localhost:5086

GET {{FranchiseGraph.Server_HostAddress}}/weatherforecast/
Accept: application/json

GET {{FranchiseGraph.Server_HostAddress}}/TMDBRequest/getTMDBCollectionData/
Accept: application/json

GET {{FranchiseGraph.Server_HostAddress}}/TMDBRequest/getMoviesFromCollection/
Accept: application/json

###
